<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8" />
			<meta http-equiv="X-UA-Compatible" content="IE=edge" />
			<meta name="description" content="" />
		    <meta name="viewport" content="width=device-width, initial-scale=1" />
			
			<base href="<?php echo $this->vista['base'] ?>" />
			
			<title><?php echo $this->vista["titulo"] ?></title>
			
            <!-- CSS -->
			<link rel="stylesheet" type="text/css"
			href="<?php echo $this->obtenerUrlVistas() ?>css/main.css" />
			
			<?php
            if ($this->vista['css_extra'] != "") $this->cargarUnaVista($this->vista['css_extra'])
            ?>
		</head>
		
		<body>
			<?php $this->cargarUnaVista($this->vista['pagina']) ?>
			
			<script type="text/javascript">
				var dirvista = '<?php echo $this->obtenerUrlVistas() ?>';
			</script>
			<script type="text/javascript"
			src="<?php echo $this->obtenerUrlVistas() ?>js/main.js"></script>
			
			<?php
            if ($this->vista['js_extra'] != "") $this->cargarUnaVista($this->vista['js_extra'])
            ?>
		</body>
	</html>
